### ISSUE TITLE
Everand urls not working

### ISSUE THREAD

**Issue by simonskok** [rkwyu/scribd-dl#3]
Hi, thank you for making this great product available on Github. The Scribd and Slideshare links work perfectly, but I am running into trouble with the podcast links on everand.com. For example:

```
node run.js https://www.everand.com/podcast/731670963/Sunday-Pick-How-to-care-for-the-people-who-take-care-of-us-w-Ai-jen-Poo-Sunday-Pick-How-to-care-for-the-people-who-take-care-of-us-w-Ai-jen-Po

file:///E:/scribd-dl/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:254
        throw new Error('Evaluation failed: ' + getExceptionMessage(exceptionDetails));
              ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'short_title')
    at eval (eval at <anonymous> (:1:8), <anonymous>:1:20)
    at pptr://__puppeteer_evaluation_script__:1:8
    at ExecutionContext._ExecutionContext_evaluate (file:///E:/scribd-dl/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:254:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (file:///E:/scribd-dl/node_modules/puppeteer-core/lib/esm/puppeteer/common/ExecutionContext.js:143:16)
    at async EverandDownloader.listen (file:///E:/scribd-dl/src/service/EverandDownloader.js:49:23)
    at async EverandDownloader.execute (file:///E:/scribd-dl/src/service/EverandDownloader.js:27:13)
    at async App.execute (file:///E:/scribd-dl/src/App.js:22:13)
    at async file:///E:/scribd-dl/run.js:16:5


```

**Comment by rkwyu** [comment]
The podcast on your Everand link (https://www.everand.com/podcast/731670963/Sunday-Pick-How-to-care-for-the-people-who-take-care-of-us-w-Ai-jen-Poo-Sunday-Pick-How-to-care-for-the-people-who-take-care-of-us-w-Ai-jen-Po) is not playable, and the page shows the message "Currently unavailable."
